# Repository settings for image-mirror

repository:
  # Repository name and description
  name: image-mirror
  description: 🔄 A powerful Docker image mirroring tool for efficient container registry management
  homepage: https://github.com/tomer1983/image-mirror
  topics: docker, container-registry, devops, python
  
  # Repository features
  has_issues: true
  has_projects: true
  has_wiki: true
  has_discussions: true
  
  # Default branch
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  
  # Security settings
  enable_vulnerability_alerts: true
  enable_automated_security_fixes: true
  
  # Branch protection rules
  branch_protection_rules:
    - pattern: main
      requirements:
        required_status_checks: true
        required_pull_request_reviews: true
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        required_linear_history: true
        allow_force_pushes: false
        allow_deletions: false
        
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation

# Social preview settings
social_preview:
  image_path: .github/social-preview.png
  alt_text: Image Mirror - Docker Registry Management Tool
