name: Import Images to Docker Hub

on:
  workflow_dispatch:

jobs:
  import-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Import images and push to Docker Hub
        run: |
          while IFS= read -r IMAGE; do
            [[ "$IMAGE" =~ ^#.*$ || -z "$IMAGE" ]] && continue
            echo "Processing $IMAGE"
            docker pull "$IMAGE"
            IMAGE_NO_REGISTRY=$(echo "$IMAGE" | awk -F/ '{print $NF}')
            docker tag "$IMAGE" "${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NO_REGISTRY"
            docker push "${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NO_REGISTRY"
          done < images-to-import.txt
